app/__init__.py
from flask import Flask
from flask_wtf.csrf import CSRFProtect

app = Flask(__name__)
app.config.from_object("config.Config")

from .home import home as home_blueprint
from .timeseries import timeseries as timeseries_blueprint


app.register_blueprint(home_blueprint)
app.register_blueprint(timeseries_blueprint)

csrf = CSRFProtect(app)

app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

from . import views

app/home/views.py
from flask import render_template
from . import home


@home.route("/home/")
@home.route("/")
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template("index.html", title="Home")

app/timeseries/__init__.py
from flask import Blueprint

timeseries = Blueprint("timeseries", __name__)

from . import views

app/timeseries/views.py
import time

from flask import (
    render_template,
    request,
    jsonify,
    make_response,
    flash,
    url_for,
    redirect,
)
import pandas
import numpy
import altair as alt
from altair.utils.data import MaxRowsError


from . import timeseries


@timeseries.route("/timeseries/", methods=["GET"])
def timeseries_ui():
    """
    Render the homepage template on the / route
    """

    return render_template("timeseries.html", title="Timeseries Builder")


@timeseries.route("/timeseries/api", methods=["GET"])
def timeseries_builder():
    """
    Render the homepage template on the / route
    """

    chart_spec = None
    chart_status = None
    msg = None

    response = {"spec": chart_spec, "chart_status": chart_status, "message": msg}

    if not request.args:
        response["message"] = "No data in request"
        return make_response(jsonify(response), 200)

    else:
        kwargs = {k: float(v) for k, v in request.args.items()}

        delay = kwargs.get("delay", 0)
        if delay > 0:
            time.sleep(delay)
        data = build_timeseries(**kwargs)

        try:
            chart_spec = make_chart(data).to_json()
            chart_status = "SUCCESS"
        except MaxRowsError:
            chart_status = "FAILURE"
            msg = "max data exceeded. Default max is 5000 data points"

        response = {"spec": chart_spec, "chart_status": chart_status, "message": msg}

        return make_response(jsonify(response), 200)


def build_timeseries(
    *,
    start=0,
    stop=100,
    n_points=100,
    amplitude=1,
    frequency=1,
    offset=0,
    noise=0,
    trend=0,
    **kwargs
):
    x = numpy.linspace(start, stop, int(n_points))
    source = pandas.DataFrame(
        {
            "x": x,
            "y": (
                offset
                + (trend * x)
                + (noise * numpy.random.uniform(-1, 1, size=x.shape))
                + amplitude * numpy.sin(x * frequency * 2 * numpy.pi)
            ),
        }
    )

    return source


def make_chart(src):
    brush = alt.selection(type="interval", encodings=["x", "y"])
    color = alt.Color("y:O", legend=None)

    line = (
        alt.Chart(src)
        .mark_line(interpolate="natural", color="lightblue", size=2)
        .encode(x=alt.X("x", title="Days"), y=alt.Y("y", title="Flowrate cfs"))
    )

    points = (
        alt.Chart(src)
        .mark_point()
        .encode(
            x="x",
            y="y",
            color=alt.condition(brush, color, alt.value("lightgray")),
            tooltip=[
                alt.Tooltip("y:Q", format=".2f", title="Flowrate"),
                alt.Tooltip("x:Q", format=".1f", title="Day"),
            ],
        )
        .add_selection(brush)
    )

    avg_line = (
        alt.Chart(src)
        .mark_rule(color="grey", opacity=0.5)
        .encode(y="mean(y):Q", size=alt.SizeValue(3),)
        .transform_filter(brush)
    )

    fit_line = line.transform_regression("x", "y").mark_line(color="firebrick")

    text = (
        alt.Chart(src)
        .mark_text(align="left", baseline="middle", x="width", dx=7,)
        .encode(y="mean(y):Q", text=alt.Text("mean(y):Q", format=".2f"))
        .transform_filter(brush)
    )

    return avg_line + line + points + fit_line + text

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

  {% if title %}
    <title>{{ title }}</title>
  {% else %}
    <title>Austin Orr</title>
  {% endif %} 
  {% endblock %}
</head>

<body>

  <div class="site">
    <div class="navigation">

        <a class='nav-button' href="{{url_for('timeseries.timeseries_ui')}}">Timeseries Builder</a>

    </div>
    <div class="content">
      {% block content %} 
      {% endblock %}
    </div>
    <footer class="footer footer-default">
      <span class="footer-copy">&copy; 2020 Geosyntec Consultants</span>
    </footer>
  </div>
</body>
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% endblock %}
</body>

</html>

app/templates/flash.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/index.html
{% extends "base.html" %} {% block content %}

<div>
	<p>
	This is a site to demonstrate the server-client architecture for injecting Vega based visuals into a dashboard.

	</p>
	
</div>

{% endblock %}

app/templates/timeseries.html
{% extends "base.html" %} 
{% block head %}
{{ super() }}
<style>
.error {
    color: red;
}

.dashboard {
	display: grid;
	grid-template-columns: 2fr 3fr;
	grid-template-rows: 1fr 5fr 2fr;
	align-items:center;
	justify-items: center;
}

.db_title {
	grid-column: 1 / -1;
}

.form_container {
	justify-self:end;
}

.db_notes {
	grid-column: 1 / -1;
}

#form-notes {
	font-size: 8pt;
	font-style: italic;
}

</style>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm//vega@5"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm//vega-lite@4.8.1"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm//vega-embed@6"></script>

{% endblock %}

{% block content %}
<div class="dashboard">
	<div class="db_title">
		<h1>Timeseries Builder</h1>
	</div>
	<div class='form_container'>
	  {% include 'ts_form.html' %}
	  
	</div>
	<div id='vis-timeseries'></div>
	<div class='db_notes'>
		<div id='form-notes'></div>
		<div id='error_msgs' ></div>
	</div>
	

</div>
{% endblock %}


{% block javascript %}
{{ super() }}
<script>

(new URL(window.location.href)).searchParams.forEach((x, y) =>
    document.getElementById(y).value = x)

function updateVegaChart(spec, id) {

	(function(vegaEmbed) {
	      
	      var embedOpt = {"mode": "vega-lite"};

	      function showError(el, error){
	          el.innerHTML = ('<div class="error" style="color:red;">'
	                          + '<p>JavaScript Error: ' + error.message + '</p>'
	                          + "<p>This usually means there's a typo in your chart specification. "
	                          + "See the javascript console for the full traceback.</p>"
	                          + '</div>');
	          throw error;
	      }
	      const el = document.getElementById(id);
	      vegaEmbed("#"+id, spec, embedOpt)
	        .catch(error => showError(el, error));
	    })(vegaEmbed);
}

const form = document.getElementById('ts-form');

form.addEventListener('submit', (evt) => {
  	evt.preventDefault();

  	const url = formToUrl("{{url_for('timeseries.timeseries_builder')}}", form);
  	const permalink = formToUrl(window.location.href.split('?')[0], form);
  	var form_notes = document.getElementById('form-notes');
  	form_notes.textContent = ('permalink: ' + permalink);

	getJsonResponse(url).then( data => {
		if (data.spec) {
			spec = JSON.parse(data.spec)
			updateVegaChart(spec, "vis-timeseries")
		} else {
			var err_div = document.getElementById('error_msgs')
			err_div.innerHTML = (
				'<div class="alert alert-warning">'
            	+ '<button type="button" class="close" data-dismiss="alert">&times;</button>'
            	+ data.message
        		+ '</div>'
			)
		}

	})
  
});

function formToUrl(url, form) {
	const formData = new FormData(form);
	formData.delete('csrf_token');
  	const params = new URLSearchParams(formData);

	return url + "?" + params.toString()
}


async function getJsonResponse(url) {

	const response = await fetch(url, {
		method: 'GET',
	})
		.then(resp => {
  		if (resp.status == 200) {
  			return resp.json();
  		} else {
  			throw new Error('got back ' + resp.status);
  		}
  	}).then(data => {
  		return data
  	});
  	return response

}
	
</script>
{% endblock %}

app/templates/ts_form.html
<form action="/timeseries" id="ts-form" method="get" enctype="text/plain">
    
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div >
        <input type="number" name ="start" id="start" value='0' step='0.01'/>
        <label for="start">Start</label>
    </div>
    <div >
        <input type="number" name ="stop" id="stop" value='10' step='0.01'/>
        <label for="stop">Stop</label>
    </div>
    <div >
        <input type="number" name ="n_points" id="n_points" value='200'>
        <label for="n_points">Number of points</label>
    </div>
    <div >
        <input type="number" name ="amplitude" id="amplitude" value='1.00' step='0.01'/>
        <label for="amplitude">Amplitude</label>
    </div>
    <div >
        <input type="number" name ="frequency" id="frequency" value='1.00' step='0.01'/>
        <label for="frequency">Frequency</label>
    </div>
    <div >
        <input type="number" name ="offset" id="offset" value='2.00' step='0.01'/>
        <label for="offset">Offset</label>
    </div>
    <div >
        <input type="number" name ="noise" id="noise" value='0.50' step='0.01'/>
        <label for="noise">Noise</label>
    </div>
    <div >
        <input type="number" name ="trend" id="trend" value='0.10' step='0.01'/>
        <label for="trend">Slope or Trend</label>
    </div>

    <div >
        <input type="number" name ="delay" id="delay" value='0.00' step='0.01'/>
        <label for="delay">mock server seconds delay</label>
    </div>

    <div>
        <button type="submit">submit</button>
    </div>

</form>